### ISSUE TITLE
Project Vision

### ISSUE THREAD

**Issue by amorriscode** [devedmonton/heyburrito#10]
👋 Hey there!

I found out about this repo from a friend and just wanted to clarify the goals of the project. I noticed it isn't a proper fork [of the original HeyBurrito](https://github.com/chralp/heyburrito).

I like the project but it isn't currently clear if I should contribute to the original or this repo. 😅

**Comment by j-rewerts** [comment]
I'd recommend contributing to the original.

**Comment by amorriscode** [comment]
Thanks for the clarification. 👍
